name: Update Contributors

on:
  schedule:
    - cron: "0 0 * * 1"  # Runs every Monday
  workflow_dispatch:  # Allows manual trigger

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Get contributors
        id: get_contributors
        run: |
          CONTRIBUTORS=$(curl -s "https://api.github.com/repos/Assesfy/MentorMind/contributors" | jq -r '.[].login' | paste -sd ", ")
          echo "contributors=$CONTRIBUTORS" >> $GITHUB_ENV

      - name: Update Repository Description
        run: |
          curl -X PATCH -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/Assesfy/MentorMind \
            -d "{\"description\": \"Contributors: $CONTRIBUTORS\"}"
